spring.application.name=UserManagement

eureka.instance.preferIpAddress=true

spring.datasource.url=jdbc:mysql://192.168.1.164:3306/userinfodb
spring.datasource.username=hfenelsoftllcai
spring.datasource.password=Dr3@m1nC0de
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
